import type { AnimNode, AnimProject, PropKey } from '@/state/types';
import { NUMERIC_PROPS } from '@/state/types';

const TRANSFORM_PROPS = new Set<PropKey>(['x', 'y', 'rotation', 'scale']);

const propLine = (
  prop: PropKey,
  value: number | string,
  duration: number,
  ease: string,
  transformOrigin?: string
): string => {
  const parts: string[] = [`duration: ${round(duration)}`];

  if (prop === 'd') parts.push(`morphSVG: ${JSON.stringify(value)}`);
  else if (prop === 'fill' || prop === 'stroke') parts.push(`${prop}: ${JSON.stringify(value)}`);
  else if (TRANSFORM_PROPS.has(prop)) {
    const num = NUMERIC_PROPS.includes(prop) && typeof value === 'string' ? Number(value) : value;
    parts.push(`${prop}: ${typeof num === 'number' ? num : JSON.stringify(num)}`);
    if (transformOrigin) parts.push(`transformOrigin: ${JSON.stringify(transformOrigin)}`);
  } else if (prop === 'opacity') {
    parts.push(`opacity: ${Number(value)}`);
  }

  parts.push(`ease: ${JSON.stringify(ease)}`);
  return `{ ${parts.join(', ')} }`;
};

const round = (n: number): string => (Math.round(n * 1000) / 1000).toString();

const collectPaths = (
  node: AnimNode,
  out: { id: string; tweens: string[]; setLines: string[] }[] = []
): typeof out => {
  if (node.tracks.length > 0) {
    const tweens: string[] = [];
    const setLines: string[] = [];

    for (const track of node.tracks) {
      const kfs = [...track.keyframes].sort((a, b) => a.time - b.time);
      if (kfs.length === 0) continue;

      const first = kfs[0];
      const transformOrigin = node.attrs['transform-origin'];

      if (track.prop === 'd') setLines.push(`gsap.set(el, { morphSVG: ${JSON.stringify(first.value)} });`);
      else if (track.prop === 'fill' || track.prop === 'stroke') setLines.push(`gsap.set(el, { ${track.prop}: ${JSON.stringify(first.value)} });`);
      else if (TRANSFORM_PROPS.has(track.prop)) {
        const v = NUMERIC_PROPS.includes(track.prop) && typeof first.value === 'string' ? Number(first.value) : first.value;
        setLines.push(`gsap.set(el, { ${track.prop}: ${typeof v === 'number' ? v : JSON.stringify(v)}${transformOrigin ? `, transformOrigin: ${JSON.stringify(transformOrigin)}` : ''} });`);
      } else if (track.prop === 'opacity') {
        setLines.push(`gsap.set(el, { opacity: ${Number(first.value)} });`);
      }

      for (let i = 0; i < kfs.length - 1; i++) {
        const a = kfs[i];
        const b = kfs[i + 1];
        const dur = Math.max(0.001, b.time - a.time);
        tweens.push(
          `tl.to(el, ${propLine(track.prop, b.value, dur, b.ease, transformOrigin)}, ${round(a.time)});`
        );
      }
    }

    if (tweens.length > 0 || setLines.length > 0) {
      out.push({ id: node.id, tweens, setLines });
    }
  }
  node.children.forEach(c => collectPaths(c, out));
  return out;
};

export const exportCode = (project: AnimProject, fnName = 'buildAnimation'): string => {
  const animatedNodes = collectPaths(project.root);
  const usesMorph = animatedNodes.some(n => n.tweens.some(t => t.includes('morphSVG')));

  const imports = [`import { gsap } from 'gsap';`];
  if (usesMorph) {
    imports.push(`import { MorphSVGPlugin } from 'gsap/MorphSVGPlugin';`);
    imports.push(`gsap.registerPlugin(MorphSVGPlugin);`);
  }

  const blocks = animatedNodes
    .map(n => {
      const lines = [
        `  // ${n.id}`,
        `  {`,
        `    const el = root.querySelector('[data-node-id="${n.id}"]');`,
        `    if (el) {`,
        ...n.setLines.map(s => `      ${s}`),
        ...n.tweens.map(t => `      ${t}`),
        `    }`,
        `  }`,
      ];
      return lines.join('\n');
    })
    .join('\n\n');

  return [
    `// generated by AnimateMo`,
    imports.join('\n'),
    ``,
    `export function ${fnName}(root: SVGSVGElement) {`,
    `  const tl = gsap.timeline({ repeat: ${project.loop ? -1 : 0}, yoyo: ${project.yoyo}, defaults: { ease: 'sine.inOut' } });`,
    ``,
    blocks,
    ``,
    `  return tl;`,
    `}`,
    ``,
  ].join('\n');
};
